import type { Action } from './models';
export const prompts: Record<Action, string> = {
  translate:
    'Translate only; do not teach grammar. Translate the input INTO TRANSLATION_LANGUAGE, regardless of source language. Never choose a target based on explanation language. Provide exactly TWO translations in this order: (1) direct: a faithful literal translation close to the original wording, while remaining understandable; (2) natural: an idiomatic expression a native speaker would use, preserving meaning and tone without adding facts. Both must use TRANSLATION_LANGUAGE. Briefly explain their differences in EXPLANATION_LANGUAGE. If both versions naturally coincide, do not invent differences.\nReturn JSON: {"source_language":"detected language name","translation_language":"exact TRANSLATION_LANGUAGE label","translations":[{"text":"literal translation","type":"direct"},{"text":"idiomatic expression","type":"natural"}],"notes":["..."]}.',
  grammar:
    'Analyze grammatical correctness of the user\'s ORIGINAL sentence in its own language. Do NOT translate the sentence before analyzing it. analysis_text must preserve the user\'s exact input, including errors; analysis_origin must be original.\nFirst check for actual grammatical errors before explaining structure: tense, agreement, word order, articles, prepositions, missing or redundant components, and other rules applicable to the input language. If any error exists, set correct=false and explicitly identify each error in corrections. original must quote the exact faulty span from the input; corrected must show the corrected span in the same language; explanation must state why it is wrong and the relevant rule, not merely say it can be improved. Use minimal corrections that preserve intended meaning. Do not classify optional stylistic improvements as grammar errors and do not invent errors in correct sentences. If correct, do not announce that there are no errors; use summary only to describe the sentence pattern. Analyze the original sentence\'s structure as well. All explanations use EXPLANATION_LANGUAGE.\nReturn JSON: {"source_language":"...","analysis_text":"exact original input","analysis_origin":"original","correct":true,"summary":"...","corrections":[{"original":"...","corrected":"...","explanation":"..."}],"structure":[{"text":"...","part":"...","role":"..."}],"grammar_points":[{"title":"...","explanation":"...","inflections":["base form","next form"]}]}.\nIf correct, corrections must be []. If incorrect, corrections must not be empty.',
  improve:
    'Evaluate the naturalness of the user\'s ORIGINAL sentence. reference_text must preserve the exact input; reference_origin must be original. Do NOT translate into another language before improving it.\nProvide natural, conversational and polite/formal alternatives IN THE SAME LANGUAGE AS THE INPUT, preserving the intended meaning. Explain tone, usage and differences in EXPLANATION_LANGUAGE. Each alternative\'s translation is an explanation-language gloss; the alternative\'s text stays in the input language.\nReturn JSON: {"source_language":"...","reference_text":"exact original input","reference_origin":"original","naturalness":"...","alternatives":[{"text":"same-language expression","style":"natural|conversational|polite","translation":"...","explanation":"..."}]}.',
};
